include("/opt/homebrew/share/cmake/Modules/GoogleTestAddTests.cmake")
gtest_discover_tests_impl(
  TEST_TARGET [==[alm_tests]==]
  TEST_EXECUTABLE [==[/Users/arstep/Projects/alm_terminal/build3/tests/alm_tests]==]
  TEST_EXECUTOR [==[]==]
  TEST_WORKING_DIR [==[/Users/arstep/Projects/alm_terminal/build3/tests]==]
  TEST_EXTRA_ARGS [==[]==]
  TEST_PROPERTIES [==[]==]
  TEST_PREFIX [==[]==]
  TEST_SUFFIX [==[]==]
  TEST_FILTER [==[]==]
  NO_PRETTY_TYPES [==[FALSE]==]
  NO_PRETTY_VALUES [==[FALSE]==]
  TEST_LIST [==[alm_tests_TESTS]==]
  CTEST_FILE [==[/Users/arstep/Projects/alm_terminal/build3/tests/alm_tests_e3b0c442_tests.cmake]==]
  TEST_DISCOVERY_TIMEOUT [==[5]==]
  TEST_DISCOVERY_EXTRA_ARGS [==[]==]
  TEST_XML_OUTPUT_DIR [==[]==]
  TEST_JSON_OUTPUT_DIR [==[/Users/arstep/Projects/alm_terminal/build3/tests]==]
)
